<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Error,could not reset your password.' => '',
  'Error,your account information was not found.
                Your reset token has probably been used or  expired.Please repeat the password reset process.' => '',
  'No user with this email in our records' => '',
  'We could not email you the password reset link' => '',
  'We have sent you a reset link,please check your email inbox.' => '',
  'Your password has been reset.Log in with your new password.' => '',
);
