<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' Något gick fel. Ditt konto kunde inte aktiveras. Var vänlig gör om registreringen.' => '',
  ', välkommen! Ditt konto är aktiverat och du kan nu logga in.' => '',
  ' Error.Your account could not be activated,please repeat the registration process.' => '@@@@',
  ',welcome! Your account has been activated.Now you can log in.' => '@@@@',
);
